# Generated by Django 4.1.11 on 2024-02-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_picture', models.ImageField(upload_to='')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_content', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=50)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_key_word', to='Blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSubContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_sub_title', models.CharField(max_length=200)),
                ('blog_sub_content', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sub_content', to='Blog.blog')),
            ],
        ),
    ]
