# Generated by Django 4.1.11 on 2024-02-20 20:05

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(upload_to=Blog.models.blog_directory_path),
        ),
    ]
